<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akash" failures="3" tests="12" name="com.Demo.AssertionDemo" time="0.971" errors="0" timestamp="2022-03-25T12:33:19 IST" skipped="9">
  <testcase classname="com.Demo.AssertionDemo" name="test1" time="0.002">
    <failure message="title is not matched expected [abc] but found [ab]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: title is not matched expected [abc] but found [ab]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.Demo.AssertionDemo.test1(AssertionDemo.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test3" time="0.004">
    <failure message="The following asserts failed:
	test3 failed expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
test3 failed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.Demo.AssertionDemo.test3(AssertionDemo.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test1" time="0.475">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test2" time="0.001">
    <failure message="The following asserts failed:
	title is not matched for test2() expected [abc] but found [ab],
	expected [false] but found [true],
	title is not matched for test2() expected [abc] but found [ab],
	expected [false] but found [true],
	title is not matched for test2() expected [abc] but found [ab],
	expected [false] but found [true],
	title is not matched for test2() expected [abc] but found [ab],
	expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
title is not matched for test2() expected [abc] but found [ab],
expected [false] but found [true],
title is not matched for test2() expected [abc] but found [ab],
expected [false] but found [true],
title is not matched for test2() expected [abc] but found [ab],
expected [false] but found [true],
title is not matched for test2() expected [abc] but found [ab],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.Demo.AssertionDemo.test2(AssertionDemo.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test2" time="0.473">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="com.Demo.AssertionDemo" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
</testsuite> <!-- com.Demo.AssertionDemo -->
